### ISSUE TITLE
Feature: Additional Encrypted Channels

### ISSUE THREAD

**Issue by memo-567** [MeshAddicts/meshinfo#40]
Nodes that exclusively use encrypted channels and therefore only send encrypted messages will not be included in the database.

**Comment by kevinelliott** [comment]
This is in progress.

**Comment by kevinelliott** [comment]
This has been added. However, still determining if we need to have the `key_hash` in the config, or if this can be dynamically calculated.

**Comment by kevinelliott** [comment]
One user on the discord confirmed that this is working! Complete for now.
