### ISSUE TITLE
Wrong link in bot response

### ISSUE THREAD

**Issue by memo-567** [MeshAddicts/meshinfo#52]
Links in responses of Mesh Bot directs to https://svm1.meshinfo.network/ instead of source / intended network.

![discord com -  2024 - 07 - 18  16 - 50](https://github.com/user-attachments/assets/e1e024a6-6558-48ce-9408-c890abda2c23)

**Comment by kevinelliott** [comment]
Fixed in https://github.com/MeshAddicts/meshinfo/commit/981c65f45978e54f4efeac1edf2049fa6e0d89ae
