### ISSUE TITLE
Meshinfo stops working after sending command to BBS

### ISSUE THREAD

**Issue by memo-567** [MeshAddicts/meshinfo#53]
`if node and chat['text'].contains('TC2 BBS') and chat['text'].contains('Available commands')`

Log attached:

[20240718-1945.txt](https://github.com/user-attachments/files/16287118/20240718-1945.txt)

**Comment by kevinelliott** [comment]
This has been fixed in https://github.com/MeshAddicts/meshinfo/releases/tag/v0.0.280
