### ISSUE TITLE
Move Caddyfile to Caddyfile.sample

### ISSUE THREAD

**Issue by kevinelliott** [MeshAddicts/meshinfo#59]
Need to make this more friendly for users.

- move `Caddyfile` to `Caddyfile.sample`
- add `Caddyfile` to `.gitignore`
- update `README.md` with `cp Caddyfile.sample Caddyfile` and instructions to edit during setup steps

**Comment by SimmerV** [comment]
You can assign this to me if you want, I'm going to start working on this :)
