### ISSUE TITLE
Docker container crash:  UnicodeDecodeError: 'utf-8' codec can't decode bytes

### ISSUE THREAD

**Issue by 1n5aN1aC** [MeshAddicts/meshinfo#63]
Getting a somewhat consistent crash of the meshinfo docker container with the following error:
`UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 1-2: invalid continuation byte`

Full log:  https://pastebin.ai/je0yo8ckb2

The container then restarts itself.  Seems to happen somewhat consistently a few times per hour.  
If you need to see the actual message being processed when it crashes, I may be able to retrieve that from the mqtt server before another one comes in and I become unsure which one is correct.

Any ideas?

**Comment by 1n5aN1aC** [comment]
Figured it out!

Someone nearby is using the PAXcounter module, which broadcasts every 15? minutes.  Anyways, meshinfo is unable to parse the json responses, and crashes when attempting to do so.

Here was one of the offending packets:

```{"channel":0,"from":4201162368,"hop_start":3,"hops_away":1,"id":1451652086,"payload":{"ble_count":0,"uptime":157808,"wifi_count":0},"rssi":-47,"sender":"!fa68a594","snr":5.75,"timestamp":1724105189,"to":4294967295,"type":"paxcounter"}```

**Comment by kevinelliott** [comment]
@1n5aN1aC I will look into getting a fix in tonight for this.

**Comment by kevinelliott** [comment]
@1n5aN1aC Are you still seeing this issue with the latest? I believe it is fixed, but want your confirmation first.

**Comment by 1n5aN1aC** [comment]
Sorry, I had missed that you had a fix in for this!

Yes, I pulled the latest, and it's been running good for over 40 minutes, which is a new record, thank you very much!!

**Comment by 1n5aN1aC** [comment]
Confirmed.

I'm at ~5 hrs uptime, whereas before even 30 minutes was impressive.

Thanks!
