### ISSUE TITLE
Handle invalid relative humidity

### ISSUE THREAD

**Issue by quimnut** [MeshAddicts/meshinfo#7]
I have some values like -4.47034800288293e-08% for relative humidity will make round(2) fail in the template.

**Comment by quimnut** [comment]
Or possibly a 0 reading causing;
meshinfo_1 |   {{ item.payload.relative_humidity | round(2) }}%
meshinfo_1 |  File “/usr/local/lib/python3.10/site-packages/jinja2/filters.py”, line 1169, in do_round

i tried not none in the template, rather than defined.

**Comment by kevinelliott** [comment]
> I have some values like -4.47034800288293e-08% for relative humidity will make round(2) fail in the template.

Thanks for submitting this.

Seems sometimes it does not appropriately detect None, which is a little strange!

**Comment by kevinelliott** [comment]
@quimnut Are you still seeing this happen? I believe this is fixed, but if not, please let me know.

**Comment by quimnut** [comment]
Maybe but it wont get as far to render that with unicode shortnames I assume this is.

meshinfo_1  | Rendering node_^B.html
meshinfo_1  | embedded null byte

**Comment by quimnut** [comment]
The only packets with valid data for node info and chat etc are the encrypted packets.

**Comment by quimnut** [comment]
purging the old json helped, updated now, looks good. "73.47%"
